# Generated by Django 3.1.12 on 2025-04-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_app', '0010_auto_20250307_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseID', models.IntegerField()),
                ('awardID', models.IntegerField()),
                ('title', models.TextField(max_length=255)),
                ('synopsis', models.TextField()),
                ('fileName', models.CharField(max_length=255)),
            ],
        ),
    ]
